[2022-05-23 21:06:31,051] {processor.py:153} INFO - Started process (PID=223) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:06:31,052] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:06:31,052] {logging_mixin.py:115} INFO - [2022-05-23 21:06:31,052] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:06:31,054] {logging_mixin.py:115} INFO - [2022-05-23 21:06:31,054] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:06:31,054] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:06:31,067] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.018 seconds
[2022-05-23 21:07:01,507] {processor.py:153} INFO - Started process (PID=363) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:07:01,507] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:07:01,507] {logging_mixin.py:115} INFO - [2022-05-23 21:07:01,507] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:07:01,509] {logging_mixin.py:115} INFO - [2022-05-23 21:07:01,508] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:07:01,509] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:07:01,520] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.015 seconds
[2022-05-23 21:07:32,014] {processor.py:153} INFO - Started process (PID=489) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:07:32,014] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:07:32,015] {logging_mixin.py:115} INFO - [2022-05-23 21:07:32,014] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:07:32,016] {logging_mixin.py:115} INFO - [2022-05-23 21:07:32,016] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:07:32,016] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:07:32,030] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.018 seconds
[2022-05-23 21:08:02,688] {processor.py:153} INFO - Started process (PID=615) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:08:02,688] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:08:02,688] {logging_mixin.py:115} INFO - [2022-05-23 21:08:02,688] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:08:02,690] {logging_mixin.py:115} INFO - [2022-05-23 21:08:02,689] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:08:02,690] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:08:02,701] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.015 seconds
[2022-05-23 21:08:33,139] {processor.py:153} INFO - Started process (PID=774) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:08:33,139] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:08:33,140] {logging_mixin.py:115} INFO - [2022-05-23 21:08:33,140] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:08:33,141] {logging_mixin.py:115} INFO - [2022-05-23 21:08:33,141] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:08:33,141] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:08:33,151] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.014 seconds
[2022-05-23 21:09:03,815] {processor.py:153} INFO - Started process (PID=858) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:09:03,815] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:09:03,815] {logging_mixin.py:115} INFO - [2022-05-23 21:09:03,815] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:09:03,816] {logging_mixin.py:115} INFO - [2022-05-23 21:09:03,816] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:09:03,817] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:09:03,827] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.014 seconds
[2022-05-23 21:09:34,279] {processor.py:153} INFO - Started process (PID=1024) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:09:34,279] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:09:34,280] {logging_mixin.py:115} INFO - [2022-05-23 21:09:34,280] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:09:34,281] {logging_mixin.py:115} INFO - [2022-05-23 21:09:34,281] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:09:34,281] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:09:34,292] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.014 seconds
[2022-05-23 21:10:04,978] {processor.py:153} INFO - Started process (PID=1109) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:10:04,978] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:10:04,978] {logging_mixin.py:115} INFO - [2022-05-23 21:10:04,978] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:10:04,980] {logging_mixin.py:115} INFO - [2022-05-23 21:10:04,979] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:10:04,980] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:10:04,991] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.015 seconds
[2022-05-23 21:10:35,455] {processor.py:153} INFO - Started process (PID=1266) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:10:35,455] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:10:35,455] {logging_mixin.py:115} INFO - [2022-05-23 21:10:35,455] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:10:35,457] {logging_mixin.py:115} INFO - [2022-05-23 21:10:35,456] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:10:35,457] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:10:35,469] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.016 seconds
[2022-05-23 21:11:06,375] {processor.py:153} INFO - Started process (PID=1348) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:11:06,375] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:11:06,376] {logging_mixin.py:115} INFO - [2022-05-23 21:11:06,376] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:11:06,379] {logging_mixin.py:115} INFO - [2022-05-23 21:11:06,378] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:11:06,379] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:11:06,402] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.034 seconds
[2022-05-23 21:11:37,022] {processor.py:153} INFO - Started process (PID=1514) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:11:37,022] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:11:37,022] {logging_mixin.py:115} INFO - [2022-05-23 21:11:37,022] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:11:37,024] {logging_mixin.py:115} INFO - [2022-05-23 21:11:37,023] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:11:37,024] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:11:37,034] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.014 seconds
[2022-05-23 21:12:07,664] {processor.py:153} INFO - Started process (PID=1596) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:12:07,664] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:12:07,665] {logging_mixin.py:115} INFO - [2022-05-23 21:12:07,665] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:12:07,666] {logging_mixin.py:115} INFO - [2022-05-23 21:12:07,666] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:12:07,666] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:12:07,677] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.015 seconds
[2022-05-23 21:12:38,169] {processor.py:153} INFO - Started process (PID=1759) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:12:38,170] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:12:38,170] {logging_mixin.py:115} INFO - [2022-05-23 21:12:38,170] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:12:38,171] {logging_mixin.py:115} INFO - [2022-05-23 21:12:38,171] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:12:38,172] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:12:38,182] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.015 seconds
[2022-05-23 21:13:08,954] {processor.py:153} INFO - Started process (PID=1841) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:13:08,955] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:13:08,955] {logging_mixin.py:115} INFO - [2022-05-23 21:13:08,955] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:13:08,957] {logging_mixin.py:115} INFO - [2022-05-23 21:13:08,956] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:13:08,957] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:13:08,968] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.016 seconds
[2022-05-23 21:13:39,424] {processor.py:153} INFO - Started process (PID=2012) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:13:39,425] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:13:39,425] {logging_mixin.py:115} INFO - [2022-05-23 21:13:39,425] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:13:39,426] {logging_mixin.py:115} INFO - [2022-05-23 21:13:39,426] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:13:39,426] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:13:39,437] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.015 seconds
[2022-05-23 21:14:10,111] {processor.py:153} INFO - Started process (PID=2094) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:14:10,112] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:14:10,112] {logging_mixin.py:115} INFO - [2022-05-23 21:14:10,112] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:14:10,114] {logging_mixin.py:115} INFO - [2022-05-23 21:14:10,114] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:14:10,115] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:14:10,130] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.021 seconds
[2022-05-23 21:14:40,709] {processor.py:153} INFO - Started process (PID=2258) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:14:40,709] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:14:40,709] {logging_mixin.py:115} INFO - [2022-05-23 21:14:40,709] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:14:40,711] {logging_mixin.py:115} INFO - [2022-05-23 21:14:40,711] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:14:40,711] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:14:40,722] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.015 seconds
[2022-05-23 21:15:10,754] {processor.py:153} INFO - Started process (PID=2341) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:15:10,756] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:15:10,757] {logging_mixin.py:115} INFO - [2022-05-23 21:15:10,757] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:15:10,758] {logging_mixin.py:115} INFO - [2022-05-23 21:15:10,758] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:15:10,759] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:15:10,778] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.026 seconds
[2022-05-23 21:15:41,465] {processor.py:153} INFO - Started process (PID=2512) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:15:41,465] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:15:41,466] {logging_mixin.py:115} INFO - [2022-05-23 21:15:41,466] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:15:41,468] {logging_mixin.py:115} INFO - [2022-05-23 21:15:41,467] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:15:41,468] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:15:41,484] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.022 seconds
[2022-05-23 21:16:12,153] {processor.py:153} INFO - Started process (PID=2586) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:16:12,154] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:16:12,154] {logging_mixin.py:115} INFO - [2022-05-23 21:16:12,154] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:16:12,156] {logging_mixin.py:115} INFO - [2022-05-23 21:16:12,155] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:16:12,156] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:16:12,170] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.019 seconds
[2022-05-23 21:16:42,902] {processor.py:153} INFO - Started process (PID=2756) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:16:42,903] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:16:42,903] {logging_mixin.py:115} INFO - [2022-05-23 21:16:42,903] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:16:42,905] {logging_mixin.py:115} INFO - [2022-05-23 21:16:42,904] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:16:42,905] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:16:42,932] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.032 seconds
[2022-05-23 21:17:13,681] {processor.py:153} INFO - Started process (PID=2838) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:17:13,681] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:17:13,681] {logging_mixin.py:115} INFO - [2022-05-23 21:17:13,681] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:17:13,683] {logging_mixin.py:115} INFO - [2022-05-23 21:17:13,683] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:17:13,683] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:17:13,694] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.015 seconds
[2022-05-23 21:17:44,177] {processor.py:153} INFO - Started process (PID=2996) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:17:44,178] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:17:44,178] {logging_mixin.py:115} INFO - [2022-05-23 21:17:44,178] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:17:44,179] {logging_mixin.py:115} INFO - [2022-05-23 21:17:44,179] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:17:44,180] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:17:44,190] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.014 seconds
[2022-05-23 21:18:15,098] {processor.py:153} INFO - Started process (PID=3080) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:18:15,098] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:18:15,099] {logging_mixin.py:115} INFO - [2022-05-23 21:18:15,099] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:18:15,100] {logging_mixin.py:115} INFO - [2022-05-23 21:18:15,100] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:18:15,100] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:18:15,111] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.015 seconds
[2022-05-23 21:18:45,601] {processor.py:153} INFO - Started process (PID=3245) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:18:45,602] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:18:45,602] {logging_mixin.py:115} INFO - [2022-05-23 21:18:45,602] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:18:45,603] {logging_mixin.py:115} INFO - [2022-05-23 21:18:45,603] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:18:45,604] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:18:45,614] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.014 seconds
[2022-05-23 21:19:16,314] {processor.py:153} INFO - Started process (PID=3329) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:19:16,314] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:19:16,314] {logging_mixin.py:115} INFO - [2022-05-23 21:19:16,314] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:19:16,316] {logging_mixin.py:115} INFO - [2022-05-23 21:19:16,316] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:19:16,316] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:19:16,328] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.016 seconds
[2022-05-23 21:19:46,782] {processor.py:153} INFO - Started process (PID=3486) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:19:46,783] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:19:46,783] {logging_mixin.py:115} INFO - [2022-05-23 21:19:46,783] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:19:46,784] {logging_mixin.py:115} INFO - [2022-05-23 21:19:46,784] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:19:46,784] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:19:46,796] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.015 seconds
[2022-05-23 21:20:17,555] {processor.py:153} INFO - Started process (PID=3569) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:20:17,555] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:20:17,555] {logging_mixin.py:115} INFO - [2022-05-23 21:20:17,555] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:20:17,557] {logging_mixin.py:115} INFO - [2022-05-23 21:20:17,556] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:20:17,557] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:20:17,568] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.015 seconds
[2022-05-23 21:20:48,032] {processor.py:153} INFO - Started process (PID=3736) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:20:48,033] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:20:48,033] {logging_mixin.py:115} INFO - [2022-05-23 21:20:48,033] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:20:48,035] {logging_mixin.py:115} INFO - [2022-05-23 21:20:48,034] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:20:48,035] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:20:48,045] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.015 seconds
[2022-05-23 21:21:18,684] {processor.py:153} INFO - Started process (PID=3818) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:21:18,685] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:21:18,685] {logging_mixin.py:115} INFO - [2022-05-23 21:21:18,685] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:21:18,686] {logging_mixin.py:115} INFO - [2022-05-23 21:21:18,686] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:21:18,687] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:21:18,698] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.015 seconds
[2022-05-23 21:21:49,168] {processor.py:153} INFO - Started process (PID=3981) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:21:49,169] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:21:49,169] {logging_mixin.py:115} INFO - [2022-05-23 21:21:49,169] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:21:49,170] {logging_mixin.py:115} INFO - [2022-05-23 21:21:49,170] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:21:49,171] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:21:49,182] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.016 seconds
[2022-05-23 21:22:19,835] {processor.py:153} INFO - Started process (PID=4060) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:22:19,835] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:22:19,835] {logging_mixin.py:115} INFO - [2022-05-23 21:22:19,835] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:22:19,837] {logging_mixin.py:115} INFO - [2022-05-23 21:22:19,836] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:22:19,837] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:22:19,847] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.014 seconds
[2022-05-23 21:22:50,301] {processor.py:153} INFO - Started process (PID=4230) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:22:50,301] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:22:50,301] {logging_mixin.py:115} INFO - [2022-05-23 21:22:50,301] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:22:50,303] {logging_mixin.py:115} INFO - [2022-05-23 21:22:50,302] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:22:50,303] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:22:50,313] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.014 seconds
[2022-05-23 21:23:20,942] {processor.py:153} INFO - Started process (PID=4312) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:23:20,943] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:23:20,943] {logging_mixin.py:115} INFO - [2022-05-23 21:23:20,943] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:23:20,945] {logging_mixin.py:115} INFO - [2022-05-23 21:23:20,944] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:23:20,945] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:23:20,955] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.014 seconds
[2022-05-23 21:23:51,483] {processor.py:153} INFO - Started process (PID=4474) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:23:51,484] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:23:51,484] {logging_mixin.py:115} INFO - [2022-05-23 21:23:51,484] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:23:51,486] {logging_mixin.py:115} INFO - [2022-05-23 21:23:51,485] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:23:51,486] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:23:51,496] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.015 seconds
[2022-05-23 21:24:22,205] {processor.py:153} INFO - Started process (PID=4558) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:24:22,205] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:24:22,205] {logging_mixin.py:115} INFO - [2022-05-23 21:24:22,205] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:24:22,207] {logging_mixin.py:115} INFO - [2022-05-23 21:24:22,206] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:24:22,207] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:24:22,218] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.015 seconds
[2022-05-23 21:24:52,675] {processor.py:153} INFO - Started process (PID=4729) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:24:52,675] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:24:52,675] {logging_mixin.py:115} INFO - [2022-05-23 21:24:52,675] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:24:52,677] {logging_mixin.py:115} INFO - [2022-05-23 21:24:52,676] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:24:52,677] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:24:52,687] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.014 seconds
[2022-05-23 21:25:23,313] {processor.py:153} INFO - Started process (PID=4808) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:25:23,314] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:25:23,314] {logging_mixin.py:115} INFO - [2022-05-23 21:25:23,314] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:25:23,315] {logging_mixin.py:115} INFO - [2022-05-23 21:25:23,315] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:25:23,316] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:25:23,327] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.015 seconds
[2022-05-23 21:25:53,827] {processor.py:153} INFO - Started process (PID=4980) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:25:53,828] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:25:53,828] {logging_mixin.py:115} INFO - [2022-05-23 21:25:53,828] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:25:53,830] {logging_mixin.py:115} INFO - [2022-05-23 21:25:53,829] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:25:53,830] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:25:53,842] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.016 seconds
[2022-05-23 21:26:24,511] {processor.py:153} INFO - Started process (PID=5053) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:26:24,511] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:26:24,511] {logging_mixin.py:115} INFO - [2022-05-23 21:26:24,511] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:26:24,513] {logging_mixin.py:115} INFO - [2022-05-23 21:26:24,513] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:26:24,513] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:26:24,528] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.019 seconds
[2022-05-23 21:26:55,046] {processor.py:153} INFO - Started process (PID=5224) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:26:55,046] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:26:55,047] {logging_mixin.py:115} INFO - [2022-05-23 21:26:55,047] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:26:55,049] {logging_mixin.py:115} INFO - [2022-05-23 21:26:55,048] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:26:55,049] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:26:55,060] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.016 seconds
[2022-05-23 21:27:25,733] {processor.py:153} INFO - Started process (PID=5306) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:27:25,733] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:27:25,733] {logging_mixin.py:115} INFO - [2022-05-23 21:27:25,733] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:27:25,735] {logging_mixin.py:115} INFO - [2022-05-23 21:27:25,734] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:27:25,735] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:27:25,745] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.014 seconds
[2022-05-23 21:27:56,223] {processor.py:153} INFO - Started process (PID=5475) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:27:56,223] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:27:56,224] {logging_mixin.py:115} INFO - [2022-05-23 21:27:56,224] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:27:56,225] {logging_mixin.py:115} INFO - [2022-05-23 21:27:56,225] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:27:56,225] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:27:56,236] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.014 seconds
[2022-05-23 21:28:26,867] {processor.py:153} INFO - Started process (PID=5546) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:28:26,867] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:28:26,867] {logging_mixin.py:115} INFO - [2022-05-23 21:28:26,867] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:28:26,869] {logging_mixin.py:115} INFO - [2022-05-23 21:28:26,869] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:28:26,869] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:28:26,880] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.015 seconds
[2022-05-23 21:28:57,415] {processor.py:153} INFO - Started process (PID=5719) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:28:57,415] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:28:57,415] {logging_mixin.py:115} INFO - [2022-05-23 21:28:57,415] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:28:57,417] {logging_mixin.py:115} INFO - [2022-05-23 21:28:57,416] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:28:57,417] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:28:57,428] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.014 seconds
[2022-05-23 21:29:28,108] {processor.py:153} INFO - Started process (PID=5799) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:29:28,109] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:29:28,109] {logging_mixin.py:115} INFO - [2022-05-23 21:29:28,109] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:29:28,110] {logging_mixin.py:115} INFO - [2022-05-23 21:29:28,110] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:29:28,111] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:29:28,121] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.014 seconds
[2022-05-23 21:29:58,646] {processor.py:153} INFO - Started process (PID=5973) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:29:58,647] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:29:58,647] {logging_mixin.py:115} INFO - [2022-05-23 21:29:58,647] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:29:58,648] {logging_mixin.py:115} INFO - [2022-05-23 21:29:58,648] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:29:58,648] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:29:58,659] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.014 seconds
[2022-05-23 21:30:29,398] {processor.py:153} INFO - Started process (PID=6043) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:30:29,398] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:30:29,399] {logging_mixin.py:115} INFO - [2022-05-23 21:30:29,399] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:30:29,400] {logging_mixin.py:115} INFO - [2022-05-23 21:30:29,400] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:30:29,400] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:30:29,411] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.015 seconds
[2022-05-23 21:30:59,887] {processor.py:153} INFO - Started process (PID=6215) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:30:59,888] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:30:59,888] {logging_mixin.py:115} INFO - [2022-05-23 21:30:59,888] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:30:59,889] {logging_mixin.py:115} INFO - [2022-05-23 21:30:59,889] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:30:59,889] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:30:59,900] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.014 seconds
[2022-05-23 21:31:30,550] {processor.py:153} INFO - Started process (PID=6292) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:31:30,550] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:31:30,551] {logging_mixin.py:115} INFO - [2022-05-23 21:31:30,551] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:31:30,552] {logging_mixin.py:115} INFO - [2022-05-23 21:31:30,552] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:31:30,552] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:31:30,563] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.014 seconds
[2022-05-23 21:32:01,150] {processor.py:153} INFO - Started process (PID=6465) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:32:01,150] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:32:01,151] {logging_mixin.py:115} INFO - [2022-05-23 21:32:01,151] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:32:01,153] {logging_mixin.py:115} INFO - [2022-05-23 21:32:01,152] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:32:01,153] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:32:01,171] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.025 seconds
[2022-05-23 21:32:31,850] {processor.py:153} INFO - Started process (PID=6541) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:32:31,850] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:32:31,851] {logging_mixin.py:115} INFO - [2022-05-23 21:32:31,851] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:32:31,853] {logging_mixin.py:115} INFO - [2022-05-23 21:32:31,852] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:32:31,853] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:32:31,867] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.020 seconds
[2022-05-23 21:33:02,367] {processor.py:153} INFO - Started process (PID=6710) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:33:02,367] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:33:02,368] {logging_mixin.py:115} INFO - [2022-05-23 21:33:02,368] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:33:02,369] {logging_mixin.py:115} INFO - [2022-05-23 21:33:02,369] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:33:02,369] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:33:02,380] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.014 seconds
[2022-05-23 21:33:33,172] {processor.py:153} INFO - Started process (PID=6788) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:33:33,172] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:33:33,173] {logging_mixin.py:115} INFO - [2022-05-23 21:33:33,173] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:33:33,174] {logging_mixin.py:115} INFO - [2022-05-23 21:33:33,174] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:33:33,174] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:33:33,184] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.014 seconds
[2022-05-23 21:34:03,688] {processor.py:153} INFO - Started process (PID=6964) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:34:03,688] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:34:03,688] {logging_mixin.py:115} INFO - [2022-05-23 21:34:03,688] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:34:03,690] {logging_mixin.py:115} INFO - [2022-05-23 21:34:03,689] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:34:03,690] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:34:03,701] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.014 seconds
[2022-05-23 21:34:34,405] {processor.py:153} INFO - Started process (PID=7044) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:34:34,405] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:34:34,406] {logging_mixin.py:115} INFO - [2022-05-23 21:34:34,406] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:34:34,407] {logging_mixin.py:115} INFO - [2022-05-23 21:34:34,407] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:34:34,407] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:34:34,418] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.015 seconds
[2022-05-23 21:35:04,887] {processor.py:153} INFO - Started process (PID=7209) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:35:04,888] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:35:04,888] {logging_mixin.py:115} INFO - [2022-05-23 21:35:04,888] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:35:04,889] {logging_mixin.py:115} INFO - [2022-05-23 21:35:04,889] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:35:04,890] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:35:04,900] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.014 seconds
[2022-05-23 21:35:35,632] {processor.py:153} INFO - Started process (PID=7287) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:35:35,632] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:35:35,632] {logging_mixin.py:115} INFO - [2022-05-23 21:35:35,632] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:35:35,634] {logging_mixin.py:115} INFO - [2022-05-23 21:35:35,633] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:35:35,634] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:35:35,645] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.014 seconds
[2022-05-23 21:36:06,120] {processor.py:153} INFO - Started process (PID=7462) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:36:06,120] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:36:06,120] {logging_mixin.py:115} INFO - [2022-05-23 21:36:06,120] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:36:06,122] {logging_mixin.py:115} INFO - [2022-05-23 21:36:06,121] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:36:06,122] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:36:06,134] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.016 seconds
[2022-05-23 21:36:36,323] {processor.py:153} INFO - Started process (PID=7541) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:36:36,323] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:36:36,323] {logging_mixin.py:115} INFO - [2022-05-23 21:36:36,323] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:36:36,325] {logging_mixin.py:115} INFO - [2022-05-23 21:36:36,324] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:36:36,325] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:36:36,346] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.025 seconds
[2022-05-23 21:37:06,788] {processor.py:153} INFO - Started process (PID=7706) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:37:06,789] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:37:06,789] {logging_mixin.py:115} INFO - [2022-05-23 21:37:06,789] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:37:06,790] {logging_mixin.py:115} INFO - [2022-05-23 21:37:06,790] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:37:06,791] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:37:06,801] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.014 seconds
[2022-05-23 21:37:37,080] {processor.py:153} INFO - Started process (PID=7784) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:37:37,081] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:37:37,081] {logging_mixin.py:115} INFO - [2022-05-23 21:37:37,081] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:37:37,082] {logging_mixin.py:115} INFO - [2022-05-23 21:37:37,082] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:37:37,083] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:37:37,095] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.016 seconds
[2022-05-23 21:38:07,648] {processor.py:153} INFO - Started process (PID=7957) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:38:07,648] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:38:07,649] {logging_mixin.py:115} INFO - [2022-05-23 21:38:07,648] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:38:07,651] {logging_mixin.py:115} INFO - [2022-05-23 21:38:07,650] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:38:07,651] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:38:07,667] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.022 seconds
[2022-05-23 21:38:38,080] {processor.py:153} INFO - Started process (PID=8028) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:38:38,080] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:38:38,080] {logging_mixin.py:115} INFO - [2022-05-23 21:38:38,080] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:38:38,082] {logging_mixin.py:115} INFO - [2022-05-23 21:38:38,082] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:38:38,082] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:38:38,093] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.016 seconds
[2022-05-23 21:39:08,537] {processor.py:153} INFO - Started process (PID=8200) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:39:08,537] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:39:08,538] {logging_mixin.py:115} INFO - [2022-05-23 21:39:08,538] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:39:08,539] {logging_mixin.py:115} INFO - [2022-05-23 21:39:08,539] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:39:08,539] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:39:08,550] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.015 seconds
[2022-05-23 21:39:38,810] {processor.py:153} INFO - Started process (PID=8278) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:39:38,811] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:39:38,811] {logging_mixin.py:115} INFO - [2022-05-23 21:39:38,811] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:39:38,813] {logging_mixin.py:115} INFO - [2022-05-23 21:39:38,812] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:39:38,813] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:39:38,828] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.020 seconds
[2022-05-23 21:40:09,299] {processor.py:153} INFO - Started process (PID=8444) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:40:09,299] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:40:09,300] {logging_mixin.py:115} INFO - [2022-05-23 21:40:09,300] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:40:09,301] {logging_mixin.py:115} INFO - [2022-05-23 21:40:09,301] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:40:09,301] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:40:09,312] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.015 seconds
[2022-05-23 21:40:39,620] {processor.py:153} INFO - Started process (PID=8522) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:40:39,621] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:40:39,621] {logging_mixin.py:115} INFO - [2022-05-23 21:40:39,621] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:40:39,622] {logging_mixin.py:115} INFO - [2022-05-23 21:40:39,622] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:40:39,623] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:40:39,634] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.016 seconds
[2022-05-23 21:41:10,096] {processor.py:153} INFO - Started process (PID=8692) to work on /opt/airflow/dags/livy_dag.py
[2022-05-23 21:41:10,097] {processor.py:641} INFO - Processing file /opt/airflow/dags/livy_dag.py for tasks to queue
[2022-05-23 21:41:10,097] {logging_mixin.py:115} INFO - [2022-05-23 21:41:10,097] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:41:10,098] {logging_mixin.py:115} INFO - [2022-05-23 21:41:10,098] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/livy_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/livy_dag.py", line 4, in <module>
    from airflow.providers.apache.livy.operators.livy import LivyOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.livy'
[2022-05-23 21:41:10,099] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/livy_dag.py
[2022-05-23 21:41:10,109] {processor.py:161} INFO - Processing /opt/airflow/dags/livy_dag.py took 0.015 seconds
